version: "3.9"

services:
  app_prod:
    depends_on:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8081:8080"
    environment:
      - BOT_TOKEN=${BOT_TOKEN_PROD}
    networks:
      - app_network

  postgres_prod:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB_PROD}
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRES_CONTAINER_NAME="postgres_prod"
    volumes:
      - postgres-prod-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres-prod-db: