version: "3.9"

services:
  app:
    depends_on: [ postgres ]
    image: app
    build:
      dockerfile: app.Dockerfile
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "economic-bot"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres-db:
    driver: local