version: "3.9"

services:
  app_test:
    depends_on: [ postgrestest ]
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - POSTGRES_HOST=158.160.9.5
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app_network

  postgres-test:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST=158.160.9.5
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres-db:
    driver: local