version: "3.9"

services:
  app:
    image: app
    build:
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "economic-bot"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"