name: EconomicBot-test-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 158.160.17.25
          username: economic-bot
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/EconomicBot/
            git pull origin main
            sudo docker-compose build
            sudo docker-compose up -d