name: EconomicBot-test-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 158.160.9.5
          username: v-pike
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
        run: |
          cd ~/EconomicBot/
          git pull origin main