name: EconomicBot-test-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Connect to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.97.59
          username: v-pike
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22